2025-06-13 11:28:03,103|[sqlalchemy_define.py: 36]|INFO|8812945152|数据库引擎已创建: sqlite:///./server_data/prize_cal.db 
2025-06-13 11:28:29,378|[sqlalchemy_define.py: 36]|INFO|8812945152|数据库引擎已创建: sqlite:///./server_data/prize_cal.db 
2025-06-13 11:29:59,846|[sqlalchemy_define.py: 36]|INFO|8812945152|数据库引擎已创建: sqlite:///server_data/prize_cal.db 
2025-06-13 11:31:23,303|[sqlalchemy_define.py: 36]|INFO|8812945152|数据库引擎已创建: sqlite:///server_data/prize_cal.db 
2025-06-13 11:31:23,315|[db_models.py: 51]|ERROR|8812945152|创建表失败: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8) 
2025-06-13 11:37:48,926|[sqlalchemy_define.py: 47]|INFO|8812945152|数据库引擎已创建: sqlite:////Users/hc/Desktop/code/toCom/big-brother-cal/cal_price_server/server_data/prize_cal.db 
2025-06-13 11:37:48,950|[db_models.py: 53]|ERROR|8812945152|创建表失败: (sqlite3.OperationalError) near "ON": syntax error
[SQL: 
CREATE TABLE t_goods_classification (
	category_id INTEGER NOT NULL, 
	main_category VARCHAR(50) NOT NULL, 
	sub_examples TEXT NOT NULL, 
	description TEXT NOT NULL, 
	temperature_req VARCHAR(100) NOT NULL, 
	hazard_level VARCHAR(100) NOT NULL, 
	storage_level VARCHAR(100) NOT NULL, 
	create_time DATETIME DEFAULT CURRENT_TIMESTAMP, 
	last_modified DATETIME DEFAULT (CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP), 
	PRIMARY KEY (category_id)
)

]
(Background on this error at: https://sqlalche.me/e/20/e3q8) 
2025-06-13 15:24:03,312|[sqlalchemy_define.py: 47]|INFO|8812945152|数据库引擎已创建: sqlite:////Users/hc/Desktop/code/toCom/big-brother-cal/cal_price_server/server_data/prize_cal.db 
2025-06-13 15:24:03,330|[db_models.py: 53]|ERROR|8812945152|创建表失败: (sqlite3.OperationalError) near "ON": syntax error
[SQL: 
CREATE TABLE t_goods_classification (
	category_id INTEGER NOT NULL, 
	main_category VARCHAR(50) NOT NULL, 
	sub_examples TEXT NOT NULL, 
	description TEXT NOT NULL, 
	temperature_req VARCHAR(100) NOT NULL, 
	hazard_level VARCHAR(100) NOT NULL, 
	storage_level VARCHAR(100) NOT NULL, 
	create_time DATETIME DEFAULT CURRENT_TIMESTAMP, 
	last_modified DATETIME DEFAULT (CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP), 
	PRIMARY KEY (category_id)
)

]
(Background on this error at: https://sqlalche.me/e/20/e3q8) 
2025-06-13 15:28:35,084|[sqlalchemy_define.py: 29]|INFO|8812945152|数据库引擎已创建: mysql+pymysql://root:****:****@127.0.0.1:3306/db_prize_cal 
2025-06-13 15:28:35,095|[sqlalchemy_define.py: 37]|ERROR|8812945152|数据库引擎创建失败: No module named 'pymysql' 
2025-06-13 15:29:34,168|[sqlalchemy_define.py: 29]|INFO|8812945152|数据库引擎已创建: mysql+pymysql://root:****:****@127.0.0.1:3306/db_prize_cal 
2025-06-16 11:17:26,231|[sqlalchemy_define.py: 29]|INFO|8812945152|数据库引擎已创建: mysql+pymysql://root:****:****@127.0.0.1:3306/db_prize_cal 
2025-06-16 11:43:07,056|[sqlalchemy_define.py: 29]|INFO|8812945152|数据库引擎已创建: mysql+pymysql://root:****:****@127.0.0.1:3306/db_prize_cal 
2025-06-16 17:11:33,017|[sqlalchemy_define.py: 29]|INFO|8812945152|数据库引擎已创建: mysql+pymysql://root:****:****@127.0.0.1:3306/db_prize_cal 
